[build]
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/get"
  to = "/.netlify/functions/getRedirect"
  status = 200

[[redirects]]
  from = "/set"
  to = "/.netlify/functions/setRedirect"
  status = 200